// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fortune.proto

package com.deviniciative.grpcFortune;

public final class FortuneProto {
  private FortuneProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FortuneRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FortuneRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FortuneReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FortuneReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rfortune.proto\"\036\n\016FortuneRequest\022\014\n\004nam" +
      "e\030\001 \001(\t\"\037\n\014FortuneReply\022\017\n\007message\030\001 \001(\t" +
      "2:\n\007Fortune\022/\n\013CallFortune\022\017.FortuneRequ" +
      "est\032\r.FortuneReply\"\000B/\n\035com.deviniciativ" +
      "e.grpcFortuneB\014FortuneProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FortuneRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FortuneRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FortuneRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_FortuneReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FortuneReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FortuneReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
