// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fortune.proto

package com.deviniciative.grpcFortune;

public interface FortuneReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FortuneReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
